"Взгляд в будущее": {
    shape: sequence_diagram
    
    
    Пользователь -> Telegram-клиент: "Запрос на анализ 'Будущее'"
    Telegram-клиент -> Исполняющий_слой: "Запрос на анализ 'Будущее'"
    Исполняющий_слой -> Внешние_сервисы: "Запрос текущих данных о криптовалютах"
    Внешние_сервисы -> Исполняющий_слой: "Ответ с данными"
    Исполняющий_слой -> СУБД: "Анализ данных и формирование прогноза"
    СУБД -> Исполняющий_слой: "Данные для прогноза"
    Исполняющий_слой -> Telegram-клиент: "Рекомендации по инвестициям"
}
