"Регистрация пользователя" : {
    shape: sequence_diagram
    Пользователь -> Telegram-клиент: Команда регистрации
    Telegram-клиент -> Исполняющий слой: Передача команды регистрации
    Исполняющий слой -> СУБД: Сохранение данных пользователя
    СУБД -> Исполняющий слой: Подтверждение сохранения
    Исполняющий слой -> Telegram-клиент: Сообщение о успешной регистрации
    Telegram-клиент -> Пользователь: Подтверждение успешной регистрации
}
