services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    working_dir: /app
    volumes:
      - ./src:/app/src
    command: python3 src/main.py
    restart: unless-stopped
    environment:
      - TOKEN_TG=${TOKEN_TG}
      - PYTHONIOENCODING=utf-8
      - PYTHONPATH=/app    
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network
networks:
  bot-network:
    driver: bridge
