services:
  telegram-bot:
    image: python:3.10.12
    container_name: telegram_bot
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    command: python src/main.py
    restart: unless-stopped
    environment:
      - TOKEN_TG=${TOKEN_TG}
      - PYTHONPATH=/app    
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network
networks:
  bot-network:
    driver: bridge
