name: Deploy buy runner

on:
  workflow_run:
    workflows: ["UnitTests Pipeline"]  
    types:
      - completed

jobs:
  prepare-environment:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down

      - name: Remove unused data
        run: docker system prune -a -f

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: docker-compose up
        run: docker-compose up -d

        
