name: UnitTests Pipeline

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev-hw03
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unittests
      run: python tests/main.py
      continue-on-error: false

    - name: Upload test results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: unittest-results
        path: ./tests